#############################################################################
# Beechcraft King Air 350ER - Pro Line Fusion flight deck (KingAir-350ER-G1000, namespace "fusion")
#
# Cockpit side of Models/Fusion/fusion-cockpit.xml (generated by Tools/fusion/gen_xml.py):
# - switch helpers used by the pick animations (positions, spring-loaded positions, guards, click sound),
# - lamps: sim/model/fusion/lamps/<name> from the conditions of Nasal/fusion-lamps.nas (same namespace),
# - the new cockpit switches (controls/fusion/...) wired to the aircraft systems: generators, DC master,
#   start / starter only, autofeather ARM / TEST, windshield heat NORMAL / HI, surface deice SINGLE / MANUAL,
#   bleed air valves, pressurization warning test, fire test, fire extinguishers,
# - functions of the Pro Line Fusion panel: flight guidance panel knobs (SPEED, HDG), autopilot coupling
#   (CPL), simplified VNAV (vertical path to the next altitude constraint of the route), YD/AP DISC,
#   propeller synchrophaser, AHRS DG FREE / SLEW, alternate static source, EMER FREQ, RADIO CALL,
#   audio panels (receivers and volumes), cabin temperature (environmental panel), flight hour meter,
#   oxygen pressure, landing gear handle lock on the ground.
#
# License: GPL v2 or later
#############################################################################

var FC = "controls/fusion/";
var fc = props.globals.getNode("controls/fusion", 1);
var lampnode = props.globals.getNode("sim/model/fusion/lamps", 1);

var click = func { setprop("sim/sound/click", !getprop("sim/sound/click")); };

# ---------------------------------------------------------------------------
# switch helpers (pick animations)
# ---------------------------------------------------------------------------
var write = func(prop, v, type) {
    var n = props.globals.getNode(prop, 1);
    if (type == "bool") n.setBoolValue(v != 0);
    elsif (type == "double") n.setDoubleValue(v);
    else n.setIntValue(v);
};

var index_of = func(values, v) {
    var best = 0;
    var d = 1e9;
    forindex (var i; values) {
        var e = math.abs(values[i] - (v or 0));
        if (e < d) { d = e; best = i; }
    }
    return best;
};

var is_momentary = func(momentary, v) {
    if (momentary == nil) return 0;
    foreach (var m; momentary) if (m == v) return 1;
    return 0;
};

# move a switch one position up (dir 1) or down (dir -1); values from the lowest position
var switch = func(prop, values, dir, type = "int", guard = nil, momentary = nil, wheel = 0) {
    if (guard != nil and !getprop(guard)) {
        gui.popupTip("Lift the guard first");
        return;
    }
    var i = index_of(values, getprop(prop));
    var j = math.clamp(i + dir, 0, size(values) - 1);
    if (j == i) return;
    write(prop, values[j], type);
    click();
    # a spring-loaded position reached with the mouse wheel is released after a short hold
    if (wheel and is_momentary(momentary, values[j]))
        settimer(func { switch_release(prop, values[size(values) > 2 ? 1 : 0], momentary, type); }, 0.7);
};

# release of the mouse button: spring-loaded positions return to rest
var switch_release = func(prop, rest, momentary, type = "int") {
    var v = getprop(prop);
    if (v == nil) return;
    if (is_momentary(momentary, v)) { write(prop, rest, type); click(); }
};

# guard cover: closing it pushes the switch back to its normal position
var guard = func(guard_prop, prop, norm, type = "int") {
    var open = !getprop(guard_prop);
    setprop(guard_prop, open);
    if (!open) write(prop, norm, type);
    click();
};

# ---------------------------------------------------------------------------
# lamps
# ---------------------------------------------------------------------------
var lamp_nodes = {};
var update_lamps = func {
    var power = (getprop("systems/electrical/volts") or 0) > 18 and cb("annunciators");
    var level = getprop(FC ~ "annun-dim") ? 0.4 : 1.0;
    foreach (var k; keys(LAMPS)) {
        if (lamp_nodes[k] == nil) lamp_nodes[k] = lampnode.getNode(k, 1);
        var on = 0;
        if (power) {
            var v = call(LAMPS[k], [], nil, nil, var err = []);
            on = (size(err) == 0 and v) ? 1 : 0;
        }
        lamp_nodes[k].setDoubleValue(on * level);
    }
};

# ---------------------------------------------------------------------------
# electrical: DC master (EMER OFF), generators ON / OFF / RESET, gen ties, bus sense
# ---------------------------------------------------------------------------
var elec = props.globals.getNode("controls/electric", 1);

var gen_switch = func(i) {
    var v = fc.getNode("gen[" ~ i ~ "]").getValue() or 0;
    if (getprop(FC ~ "master-emer") and v != 0) return;
    elec.getNode("engine[" ~ i ~ "]/bus-tie", 1).setBoolValue(v == 1);
};

var master_emer = func {
    if (!getprop(FC ~ "master-emer")) return;
    elec.getNode("battery-switch", 1).setBoolValue(0);
    foreach (var i; [0, 1]) elec.getNode("engine[" ~ i ~ "]/bus-tie", 1).setBoolValue(0);
    gui.popupTip("DC master: EMERGENCY OFF (battery and generators disconnected)");
};

# ---------------------------------------------------------------------------
# engines: IGNITION AND ENGINE START (ON / OFF / STARTER ONLY), autofeather ARM / OFF / TEST
# ---------------------------------------------------------------------------
var start_switch = func(i) {
    var v = fc.getNode("start[" ~ i ~ "]").getValue() or 0;
    var ctl = props.globals.getNode("controls/engines/engine[" ~ i ~ "]", 1);
    if (v != 0 and !(getprop("controls/electric/battery-switch") or getprop("controls/electric/external-power"))) {
        gui.popupTip("Starter: no electrical power (battery OFF)");
    }
    if (!cb("start[" ~ i ~ "]")) v = 0;
    ctl.getNode("starter-only", 1).setBoolValue(v == -1);
    ctl.getNode("starter", 1).setBoolValue(v != 0);
};

var autofeather_switch = func {
    var v = getprop(FC ~ "autofeather") or 0;
    if (!cb("autofeather")) v = 0;
    setprop("controls/engines/autofeather", v != 0);
    setprop("controls/engines/autofeather-test", v == -1);
};

# ---------------------------------------------------------------------------
# ice protection: windshield NORMAL / OFF / HI, surface deice SINGLE / MANUAL
# ---------------------------------------------------------------------------
var wshld_switch = func(i) {
    var v = fc.getNode("wshld[" ~ i ~ "]").getValue() or 0;
    setprop("controls/anti-ice/window-heat[" ~ i ~ "]", v != 0);
    setprop("controls/anti-ice/window-heat-hi[" ~ i ~ "]", v == -1);
};

var surface_deice = func {
    var v = getprop(FC ~ "surface-deice") or 0;
    setprop("controls/anti-ice/wing-deice-cycle", v != 0);
};

# ---------------------------------------------------------------------------
# bleed air valves: OPEN / ENVIR OFF / PNEU & ENVIR OFF; pressurization warning test; fire test and extinguishers
# ---------------------------------------------------------------------------
var bleed_switch = func(i) {
    var v = fc.getNode("bleed[" ~ i ~ "]").getValue();
    if (v == nil) v = 1;
    if (!cb("bleed[" ~ i ~ "]")) v = 1;          # the valves fail open without power
    setprop("controls/pressurization/bleed-air[" ~ i ~ "]", v == 1);
    setprop("controls/pressurization/pneumatic[" ~ i ~ "]", v >= 0);
};

var cabin_test = func {
    var v = getprop(FC ~ "cabin-warn-test") or 0;
    setprop("controls/pressurization/cabin-alt-test", v == 1);
    setprop("controls/pressurization/diff-warn-test", v == -1);
};

var fire_extinguisher = func(eng) {
    var n = fc.getNode("extinguisher[" ~ eng ~ "]", 1);
    if (n.getBoolValue()) { gui.popupTip("Fire extinguisher already discharged"); return; }
    n.setBoolValue(1);
    # the extinguisher closes the firewall valve of that engine (valve breaker in)
    if (cb("fw-valve[" ~ eng ~ "]")) setprop("controls/engines/engine[" ~ eng ~ "]/fire-handle", 1);
    click();
    gui.popupTip((eng == 0 ? "Left" : "Right") ~ " engine fire extinguisher DISCHARGED, firewall valve closed");
};

# ---------------------------------------------------------------------------
# flight guidance panel
# ---------------------------------------------------------------------------
var speed_knob = func(dir) {
    var n = props.globals.getNode("autopilot/settings/target-speed-kt", 1);
    n.setDoubleValue(math.clamp((n.getValue() or 150) + dir, 80, 263));
    FCS.annunciate();
};

var speed_sync = func {
    setprop("autopilot/settings/target-speed-kt", math.round(getprop("instrumentation/airspeed-indicator/indicated-speed-kt") or 150));
    FCS.annunciate();
};

var heading_knob = func(dir) {
    var n = props.globals.getNode("instrumentation/fgc-65/settings/hdg", 1);
    var h = math.round((n.getValue() or 0) + dir);
    while (h < 0) h += 360;
    while (h >= 360) h -= 360;
    n.setDoubleValue(h);
};

var heading_sync = func {
    setprop("instrumentation/fgc-65/settings/hdg", math.round(getprop("orientation/heading-magnetic-deg") or 0));
};

var baro_std = func(dev) {
    setprop("instrumentation/altimeter/setting-inhg", 29.92);
    gui.popupTip("Altimeter STD (29.92 inHg)");
};

var ap_yd_disconnect = func {
    FCS.engage(0);
    if (getprop("controls/flight/yaw-damper")) kingair350.toggle_yaw_damper();
    setprop(FC ~ "vnav", 0);
};

# CPL: the autopilot follows the navigation source of the pilot PFD (left) or of the copilot PFD (right)
var cdi_source = {1: "GPS", 3: "GPS"};
var set_cdi_source = func(dev, src) {
    cdi_source[dev] = src;
    if (dev == ((getprop(FC ~ "couple") or 0) ? 3 : 1)) FCS.set_nav_source(src);
};
var couple_toggle = func {
    var c = !(getprop(FC ~ "couple") or 0);
    setprop(FC ~ "couple", c);
    FCS.set_nav_source(cdi_source[c ? 3 : 1]);
    gui.popupTip("Autopilot coupled to the " ~ (c ? "copilot" : "pilot") ~ " PFD (" ~ cdi_source[c ? 3 : 1] ~ ")");
};

# VNAV: vertical path to the next waypoint of the active route that has an altitude constraint. The autopilot flies
# VS with the altitude pre-select set to the constraint (captured by ALTS); the rate is recomputed along the leg.
var vnav_target = nil;
var vnav = func {
    if (getprop(FC ~ "vnav")) { setprop(FC ~ "vnav", 0); gui.popupTip("VNAV off"); return; }
    var t = vnav_next();
    if (t == nil) { gui.popupTip("VNAV: no altitude constraint ahead in the active flight plan"); return; }
    setprop(FC ~ "vnav", 1);
    vnav_target = t;
    setprop("autopilot/settings/target-alt-ft", t.alt);
    if (FCS.vertical != "VS") FCS.btn_pressed("vs", 1, 0);
    gui.popupTip(sprintf("VNAV: %s at %i ft", t.id, t.alt));
};
var vnav_next = func {
    if (!getprop("autopilot/route-manager/active")) return nil;
    var n = getprop("autopilot/route-manager/route/num") or 0;
    var cur = getprop("autopilot/route-manager/current-wp") or 0;
    var dist = 0;
    for (var i = cur; i < n; i += 1) {
        var wp = props.globals.getNode("autopilot/route-manager/route/wp[" ~ i ~ "]");
        if (wp == nil) break;
        dist = (i == cur) ? (getprop("autopilot/route-manager/wp/dist") or 0) : dist + (wp.getNode("leg-distance-nm", 1).getValue() or 0);
        var alt = wp.getNode("altitude-ft", 1).getValue() or -9999;
        if (alt > 0) return {id: wp.getNode("id", 1).getValue() or "WPT", alt: alt, dist: dist, index: i};
    }
    return nil;
};
var update_vnav = func {
    if (!getprop(FC ~ "vnav")) return;
    var t = vnav_next();
    if (t == nil or !FCS.engaged and !FCS.fd_on) { setprop(FC ~ "vnav", 0); return; }
    var alt = getprop("instrumentation/altimeter/indicated-altitude-ft") or 0;
    var gs = math.max(60, getprop("velocities/groundspeed-kt") or 150);
    var dh = t.alt - alt;
    if (math.abs(dh) < 50 or FCS.vertical == "ALT") return;
    var minutes = math.max(0.5, t.dist / gs * 60);
    var vs = math.clamp(math.round(dh / minutes / 100) * 100, -2500, 2000);
    setprop("autopilot/settings/target-alt-ft", t.alt);
    setprop("autopilot/settings/vertical-speed-fpm", vs);
};

# ---------------------------------------------------------------------------
# propeller synchrophaser: the right governor follows the left propeller speed (+-25 rpm authority)
# ---------------------------------------------------------------------------
var sync_trim = 0.0;
var update_prop_sync = func {
    var on = getprop(FC ~ "prop-sync") and cb("prop-sync") and dc_ok() and getprop("engines/engine[0]/running")
             and getprop("engines/engine[1]/running");
    if (!on) {
        if (sync_trim != 0) { sync_trim = 0; setprop("fdm/jsbsim/fcs/prop-sync-trim", 0); }
        return;
    }
    var r0 = getprop("engines/engine[0]/rpm") or 0;
    var r1 = getprop("engines/engine[1]/rpm") or 0;
    if (math.abs(r0 - r1) > 60) return;      # out of capture range
    sync_trim = math.clamp(sync_trim + (r0 - r1) * 0.0002, -0.1, 0.1);
    setprop("fdm/jsbsim/fcs/prop-sync-trim", sync_trim);
};

# ---------------------------------------------------------------------------
# AHRS heading: slaved to the magnetic heading, or a free directional gyro (DG FREE) that drifts and is slewed
# with the SLEW switch. Published to the FG1000 as its heading (Nasal/fg1000-kingair-interfaces.nas).
# ---------------------------------------------------------------------------
var dg_offset = 0.0;
var update_ahrs = func(dt) {
    var free = getprop(FC ~ "dg-free[0]") or getprop(FC ~ "dg-free[1]");
    if (free) {
        dg_offset += dt * 0.004;          # ~15 deg per hour of apparent drift
        foreach (var k; [0, 1]) dg_offset += (getprop(FC ~ "slew[" ~ k ~ "]") or 0) * dt * 3.0;
    } else {
        dg_offset = 0;
    }
    var h = (getprop("orientation/heading-magnetic-deg") or 0) + dg_offset;
    while (h < 0) h += 360;
    while (h >= 360) h -= 360;
    setprop("instrumentation/fusion/ahrs-heading-deg", h);
};

# ---------------------------------------------------------------------------
# alternate static source: the pilot static system reads the cabin pressure
# ---------------------------------------------------------------------------
var update_static = func {
    var alt = getprop("controls/switches/alt-static");
    var n = props.globals.getNode("systems/static", 1);
    if (!alt) {
        if (!n.getNode("serviceable", 1).getBoolValue()) n.getNode("serviceable").setBoolValue(1);
        return;
    }
    n.getNode("serviceable", 1).setBoolValue(0);
    var cab = getprop("systems/pressurization/cabin-altitude-ft") or (getprop("position/altitude-ft") or 0);
    # unpressurized cabin: slight suction (reads ~30 ft high); pressurized: the cabin altitude
    var p = 29.92126 * math.pow(1 - (cab + 30) / 145442.16, 5.25588);
    n.getNode("pressure-inhg", 1).setDoubleValue(p);
};

# ---------------------------------------------------------------------------
# audio panels: receivers pulled on with their volume, the louder of the two panels wins
# ---------------------------------------------------------------------------
var RX = {"comm1": ["instrumentation/comm[0]/volume"], "comm2": ["instrumentation/comm[1]/volume"],
          "nav1": ["instrumentation/nav[0]/volume"], "nav2": ["instrumentation/nav[1]/volume"],
          "dme1": ["instrumentation/dme/volume"], "dme2": [],
          "adf": ["instrumentation/adf/volume-norm"], "mkr": ["instrumentation/marker-beacon/volume"], "pa": []};
var update_audio = func {
    foreach (var r; keys(RX)) {
        var v = 0;
        foreach (var k; [0, 1]) {
            if (!cb(k == 0 ? "audio-panel" : "audio-panel[1]") or !dc_ok()) continue;
            var a = "controls/fusion/audio[" ~ k ~ "]/";
            if (getprop(a ~ r)) v = math.max(v, (getprop(a ~ r ~ "-vol") or 0) * (getprop(a ~ "master-vol") or 0));
        }
        foreach (var p; RX[r]) setprop(p, v);
    }
    # NAV / DME / ADF identification audio: IDENT or BOTH on the pilot panel filter
    var filt = getprop("controls/fusion/audio[0]/filter");
    var ident = (filt == nil or filt <= 1);
    foreach (var p; ["instrumentation/nav[0]/ident", "instrumentation/nav[1]/ident", "instrumentation/dme/ident",
                     "instrumentation/adf/ident-audible"]) setprop(p, ident);
    setprop("instrumentation/marker-beacon/audio-btn", getprop("controls/fusion/audio[0]/mkr") or getprop("controls/fusion/audio[1]/mkr"));
};

# push to talk (control wheel trigger): transmits on the radio of that side's XMT selector (1, 2; PA and HF have no
# FlightGear radio), lights the T annunciator of the audio panel
var ptt = func(side, on) {
    setprop(FC ~ "ptt[" ~ side ~ "]", on);
    var x = getprop("controls/fusion/audio[" ~ side ~ "]/xmit") or 0;
    if (getprop("controls/fusion/audio[" ~ side ~ "]/emer")) x = 0;      # EMER: COM 1 direct
    if (x <= 1) controls.ptt(on ? x + 1 : 0);
};

var emer_freq = func {
    setprop("instrumentation/comm[0]/frequencies/selected-mhz", 121.5);
    gui.popupTip("COM 1: 121.500 (emergency)");
};

# RADIO CALL: an ATC message heard on the radio lights the annunciator until it is pressed
setlistener("sim/messages/atc", func {
    if ((getprop("systems/electrical/outputs/comm") or 0) > 15 and (getprop("instrumentation/comm[0]/volume") or 0) > 0.05)
        setprop(FC ~ "radio-call", 1);
}, 0, 0);

# ---------------------------------------------------------------------------
# environmental panel: cabin temperature (bleed air heating / refrigeration, electric heat on the ground)
# ---------------------------------------------------------------------------
var cabin_t = nil;
var update_cabin = func(dt) {
    var oat = getprop("environment/temperature-degc") or 15;
    if (cabin_t == nil) cabin_t = oat;
    var mode = getprop(FC ~ "env/mode");
    if (mode == nil) mode = 1;
    var bleed = getprop("systems/pressurization/bleed-air[0]") or getprop("systems/pressurization/bleed-air[1]");
    var dc = (getprop("systems/electrical/volts") or 0) > 20 and cb("temp-control");
    var target = oat;
    var tau = 900.0;                                   # leak towards the outside
    if (dc and mode != 0) {
        var sel = 16 + 14 * (getprop(FC ~ "env/temp-cockpit") or 0.5) * 0.5 + 14 * (getprop(FC ~ "env/temp-cabin") or 0.5) * 0.5;
        if (mode == 1 and bleed) { target = sel; tau = 180; }
        elsif (mode == 2) { target = math.min(oat, 12); tau = 240; }                     # MAN COOL (vapour cycle)
        elsif (mode == 3 and bleed) { target = 20 + 12 * (getprop(FC ~ "env/man-heat") or 0.5); tau = 200; }   # MAN HEAT
        elsif (mode == 4 and getprop("gear/gear[1]/wow") and cb("elec-heat")) { target = 24; tau = 400; }   # ELEC HEAT (ground)
        # blowers (AUTO / LO / HI): faster mixing, none without their breakers
        var blow = 0;
        foreach (var k; [0, 1])
            if (cb("blower[" ~ k ~ "]")) blow += 0.5 + 0.25 * (getprop(FC ~ (k == 0 ? "env/blower-cockpit" : "env/blower-cabin")) or 0);
        tau = tau / math.max(0.3, blow);
    }
    cabin_t += (target - cabin_t) * math.min(1, dt / tau);
    setprop("systems/environment/cabin-temp-degc", cabin_t);
    # MAN TEMP INCR / DECR moves the manual heat valve
    var mt = getprop(FC ~ "env/man-temp") or 0;
    if (mt != 0) setprop(FC ~ "env/man-heat", math.clamp((getprop(FC ~ "env/man-heat") or 0.5) + mt * dt * 0.1, 0, 1));
};

# ---------------------------------------------------------------------------
# flight hour meter (runs in flight), oxygen bottle
# ---------------------------------------------------------------------------
var hobbs = props.globals.getNode("sim/model/fusion/hobbs-hours", 1);
var update_hobbs = func(dt) {
    var h = hobbs.getValue() or 1248.3;
    if (!getprop("gear/gear[1]/wow") and cb("hobbs") and dc_ok()) h += dt / 3600.0;
    hobbs.setDoubleValue(h);
    var t = h;
    var d = [math.mod(math.floor(t / 1000), 10), math.mod(math.floor(t / 100), 10), math.mod(math.floor(t / 10), 10),
             math.mod(math.floor(t), 10), math.mod(t * 10, 10)];
    forindex (var k; d) setprop("sim/model/fusion/hobbs/d" ~ k, d[k]);
};

# ---------------------------------------------------------------------------
# landing gear handle: locked down on the ground unless DOWN LOCK REL is held
# ---------------------------------------------------------------------------
var gear_handle = func {
    if (getprop("controls/gear/gear-down")) {
        if ((getprop("gear/gear[1]/wow") or getprop("gear/gear[2]/wow")) and !getprop("controls/gear/downlock-release")) {
            gui.popupTip("Landing gear handle locked DOWN on the ground (hold DOWN LOCK REL to override)");
            return;
        }
        if ((getprop("controls/fusion/cb/landing-gear-relay") or 0)) { gui.popupTip("LANDING GEAR RELAY circuit breaker pulled"); return; }
        controls.gearDown(-1);
    } else {
        if ((getprop("controls/fusion/cb/landing-gear-relay") or 0)) { gui.popupTip("LANDING GEAR RELAY circuit breaker pulled"); return; }
        controls.gearDown(1);
    }
    click();
};

# ---------------------------------------------------------------------------
# pedestal: power levers (forward range, then beta / reverse behind IDLE on the ground), paired levers
# ---------------------------------------------------------------------------
var power_lever = func(i, off) {
    foreach (var e; (i < 0) ? [0, 1] : [i]) {
        var c = props.globals.getNode("controls/engines/engine[" ~ e ~ "]", 1);
        var thr = c.getNode("throttle", 1).getValue() or 0;
        var pos = c.getNode("reverser", 1).getBoolValue() ? -thr : thr;
        var np = math.clamp(pos + 0.02 * off, -1, 1);
        if (pos >= 0 and np < 0) {
            if (!getprop("gear/gear[1]/wow")) { np = 0; gui.popupTip("Beta / reverse: on the ground only"); }
            elsif (!getprop("engines/engine[" ~ e ~ "]/running")) { np = 0; gui.popupTip("Reverse only with the engines running"); }
        }
        c.getNode("reverser", 1).setBoolValue(np < 0);
        c.getNode("throttle", 1).setDoubleValue(math.abs(np));
    }
};

var lever_both = func(name, step, off) {
    foreach (var e; [0, 1]) {
        var n = props.globals.getNode("controls/engines/engine[" ~ e ~ "]/" ~ name, 1);
        n.setDoubleValue(math.clamp((n.getValue() or 0) + step * off, 0, 1));
    }
};

var update_power_levers = func {
    foreach (var e; [0, 1]) {
        var c = "controls/engines/engine[" ~ e ~ "]/";
        var thr = getprop(c ~ "throttle") or 0;
        setprop("sim/model/fusion/power-lever[" ~ e ~ "]", getprop(c ~ "reverser") ? -thr : thr);
    }
};

# GO AROUND (left power lever): autopilot off, flight director wings level and 7 deg nose up
var go_around = func {
    FCS.engage(0);
    FCS.fd_on = 1;
    FCS.lateral = "";
    FCS.lat_armed = "";
    FCS.gs_armed = 0;
    FCS.vertical = "PIT";
    FCS.alt_armed = 1;
    FCS.set_target_pitch(7);
    FCS.annunciate();
    setprop(FC ~ "vnav", 0);
    click();
    gui.popupTip("GO AROUND: flight director wings level, 7 deg nose up");
};

# landing gear warning horn: gear not down and locked with a power lever retarded (silenceable, re-armed when the
# power levers are advanced) or with the flaps beyond APPROACH (cannot be silenced); test switch
var horn_silenced = 0;
var update_gear_horn = func {
    var down = 1;
    foreach (var g; [0, 1, 2]) if ((getprop("gear/gear[" ~ g ~ "]/position-norm") or 0) < 0.999) down = 0;
    var dc = (getprop("systems/electrical/volts") or 0) > 20 and cb("gear-warn");
    var thr = math.min(getprop("controls/engines/engine[0]/throttle") or 0, getprop("controls/engines/engine[1]/throttle") or 0);
    var low_power = thr < 0.15 and !getprop("gear/gear[1]/wow");
    var flaps = (getprop("surface-positions/flap-pos-norm") or 0) > 0.5;
    if (thr > 0.35) horn_silenced = 0;
    var horn = dc and !down and ((low_power and !horn_silenced) or flaps);
    horn = horn or (dc and getprop(FC ~ "gear-warn-test"));
    setprop(FC ~ "gear-warn", horn);
    setprop("sim/sound/gear-warn", horn);
};
var gear_horn_silence = func {
    if ((getprop("surface-positions/flap-pos-norm") or 0) > 0.5) gui.popupTip("Gear horn: cannot be silenced with the flaps DOWN");
    else horn_silenced = 1;
    click();
};

# electric pitch trim (control wheel switches), ELEV TRIM switch on the pedestal
var trim = func(dir) {
    if (!(getprop(FC ~ "elec-trim") or 0) or !cb("elec-trim") or (getprop("systems/electrical/volts") or 0) < 20) {
        gui.popupTip("Electric pitch trim OFF");
        return;
    }
    if (FCS.engaged) FCS.engage(0);         # trim interrupt disconnects the autopilot
    controls.elevatorTrim(dir);
};

# ---------------------------------------------------------------------------
# cursor control panels and multifunction keyboard -> FG1000 (display chosen on each panel, CURSOR inhibit)
# ---------------------------------------------------------------------------
var INHIBIT = {1: "pfd1", 2: "mfd", 3: "pfd2"};
var last_ccp = 0;
var ccp_device = func(side) {
    var d = getprop(FC ~ "ccp[" ~ side ~ "]/display") or 0;
    return side == 0 ? (d ? 2 : 1) : (d ? 3 : 2);
};
var fg1000_key = func(dev, key, off) {
    if (!cb("ccp") or !dc_ok()) { gui.popupTip("Cursor control panels and keyboard: no power (CCP MKP breaker)"); return; }
    if ((getprop(FC ~ "inhibit-" ~ INHIBIT[dev]) or 0) == -1) {
        gui.popupTip("Cursor control inhibited on " ~ ["", "PFD 1", "the MFD", "PFD 2"][dev]);
        return;
    }
    fgcommand("FG1000HardKeyPushed", props.Node.new({"device": dev, "notification": key, "offset": off}));
};
var ccp = func(side, key, off = 1) {
    last_ccp = side;
    fg1000_key(ccp_device(side), key, off);
};
var mkp = func(ch) { fg1000_key(ccp_device(last_ccp), "KEY_INPUT", ch); };
var mkp_key = func(key, off = 1) { fg1000_key(ccp_device(last_ccp), key, off); };

# ---------------------------------------------------------------------------
# touch radio boxes of the PFDs (kind NAV or COM, line 1 or 2): "select" makes that radio the one tuned (cyan box),
# "tune" moves its standby frequency (mouse wheel: MHz, with shift: kHz), "swap" exchanges its active and standby
# frequencies. The FG1000 acts on the selected radio only, so the line is selected first.
# ---------------------------------------------------------------------------
var PFD_POWER = {1: "fg1000-pfd", 3: "fg1000-pfd2"};
var radio_touch = func(dev, kind, line, action, dir = 0) {
    if ((getprop("systems/electrical/outputs/" ~ PFD_POWER[dev]) or 0) < 20) return;
    var key = func(k, off = 1) fgcommand("FG1000HardKeyPushed", props.Node.new({"device": dev, "notification": k, "offset": off}));
    if ((getprop("instrumentation/" ~ (kind == "NAV" ? "nav" : "com") ~ "-selected") or 1) != line) key(kind ~ "_TOGGLE");
    if (action == "swap") key(kind ~ "_FREQ_TRANSFER");
    elsif (action == "tune") key(kind ~ (getprop("devices/status/keyboard/shift") ? "_INNER" : "_OUTER"), dir);
};

# ---------------------------------------------------------------------------
# pressurization controller switch, cockpit voice recorder
# ---------------------------------------------------------------------------
var cabin_press = func {
    var v = getprop(FC ~ "cabin-press") or 0;
    setprop("controls/pressurization/cabin-press", v == 1 ? "dump" : (v == -1 ? "test" : "press"));
};
var cvr_t = 0;
var update_cvr = func(dt) {
    if (getprop(FC ~ "cvr-test") and cb("cvr") and (getprop("systems/electrical/volts") or 0) > 20) cvr_t += dt;
    else cvr_t = 0;
    setprop(FC ~ "cvr-ok", cvr_t > 1.0);
};
var cvr_erase = func {
    if (getprop("gear/gear[1]/wow") and getprop("controls/gear/brake-parking")) gui.popupTip("Cockpit voice recorder erased");
    else gui.popupTip("CVR erase: on the ground with the parking brake set only");
};

# ---------------------------------------------------------------------------
# circuit breakers (side panels): controls/fusion/cb/<id> = 1 when pulled. The shared systems read them too
# (electrical.nas, ice-protection.nas, kingair350.nas, annunciators.nas, pressurization.nas).
# ---------------------------------------------------------------------------
var cb = func(id) { !getprop("controls/fusion/cb/" ~ id); };
var dc_ok = func { (getprop("systems/electrical/volts") or 0) > 20; };

# functions whose switch position is kept while their breaker is pulled: the system is forced off, then restored
var cb_saved = {};
var cb_force_off = func(id, prop) {
    if (!cb(id)) {
        if (cb_saved[id] == nil) cb_saved[id] = getprop(prop) ? 1 : 0;
        if (getprop(prop)) setprop(prop, 0);
    } elsif (cb_saved[id] != nil) {
        setprop(prop, cb_saved[id]);
        cb_saved[id] = nil;
    }
};

# DC loads without a system model of their own (A), added by Nasal/electrical.nas
var load_amps = func {
    var a = 0;
    if (getprop(FC ~ "window-defog") and cb("window-defog")) a += 7;
    var cl = getprop(FC ~ "cabin-lights") or 0;
    if (cl and cb("cabin-lights")) a += 5 * cl;
    if (getprop("controls/lighting/ice-light") and cb("ice-light")) a += 4;
    foreach (var i; [0, 1]) if (getprop("controls/fuel/stby-pump[" ~ i ~ "]")) a += 5;
    var mode = getprop(FC ~ "env/mode") or 0;
    if (mode != 0)
        foreach (var k; [0, 1])
            if (cb("blower[" ~ k ~ "]")) a += 6 + 4 * (getprop(FC ~ (k == 0 ? "env/blower-cockpit" : "env/blower-cabin")) or 0);
    return a;
};

var flap_hold = nil;
var gear_hold = nil;
var update_cbs = func {
    cb_force_off("rudder-boost", "controls/flight/rudder-boost");
    cb_force_off("yaw-damper", "controls/flight/yaw-damper");
    # flaps: no motor or no control, the flaps stay where they are
    var fl = getprop("controls/flight/flaps") or 0;
    if (!cb("flap-motor") or !cb("flap-control")) {
        if (flap_hold == nil) flap_hold = getprop("surface-positions/flap-pos-norm") or fl;
        if (math.abs(fl - flap_hold) > 0.001) setprop("controls/flight/flaps", flap_hold);
    } else flap_hold = nil;
    # landing gear control: the handle does nothing
    var gd = getprop("controls/gear/gear-down");
    if (!cb("gear-control") or !cb("gear-relay")) {
        if (gear_hold == nil) gear_hold = gd;
        if (gd != gear_hold) setprop("controls/gear/gear-down", gear_hold);
    } else gear_hold = nil;
    # autopilot servos
    if (!cb("autopilot") and FCS.engaged) { FCS.engage(0); gui.popupTip("Autopilot: servo power lost (AP SERVOS breaker)"); }
    # propeller overspeed governor test
    if (!cb("prop-gov-test") and getprop("controls/engines/prop-overspeed-test")) setprop("controls/engines/prop-overspeed-test", 0);
    # starters
    foreach (var i; [0, 1])
        if (!cb("start[" ~ i ~ "]") and getprop("controls/engines/engine[" ~ i ~ "]/starter"))
            setprop("controls/engines/engine[" ~ i ~ "]/starter", 0);
};

# ---------------------------------------------------------------------------
# overhead: panel lights, flood lights, display brightness, annunciator dimming, cabin signs
# ---------------------------------------------------------------------------
var update_lighting = func {
    var master = getprop("controls/lighting/master-panel") and dc_ok();
    setprop("sim/model/fusion/panel-lights-norm", master and cb("instrument-lights")
            ? math.clamp(getprop("controls/lighting/instruments-norm") or 0, 0, 1) : 0);
    foreach (var z; [0, 1, 2])
        setprop("sim/model/fusion/flood-norm[" ~ z ~ "]",
                (master and cb("flood")) ? math.clamp(getprop("sim/model/fusion/flood[" ~ z ~ "]") or 0, 0, 1) : 0);
};

var cabin_signs = func {
    if (!dc_ok() or !cb("cabin-signs")) return;
    setprop("sim/sound/cabin-chime", 1);
    settimer(func setprop("sim/sound/cabin-chime", 0), 1.0);
    var v = getprop(FC ~ "cabin-signs") or 0;
    setprop("sim/model/fusion/signs/seatbelt", v >= 1);
    setprop("sim/model/fusion/signs/no-smoking", v >= 2);
};

# ---------------------------------------------------------------------------
# fuel panel: crossfeed, standby pumps, aux transfer, quantity gauges (MAIN / AUX / TEST)
# ---------------------------------------------------------------------------
var crossfeed_switch = func {
    var v = getprop(FC ~ "crossfeed") or 0;
    if (!cb("crossfeed") or !dc_ok()) v = 0;
    # cockpit LEFT: the right main feeds the left engine (crossfeed -1); RIGHT: the left main feeds the right engine
    setprop("controls/fuel/transfer", v == 1 ? "left" : (v == -1 ? "right" : "off"));
};

var update_fuel = func {
    foreach (var i; [0, 1]) {
        var x = getprop(FC ~ "aux-xfer[" ~ i ~ "]");
        if (x == nil) x = 0;
        var on = (x == 1) or (x == 0 and cb("aux-xfer[" ~ i ~ "]"));      # OVERRIDE bypasses the automatic control
        setprop(i == 0 ? "controls/fuel/Laux-switch" : "controls/fuel/Raux-switch", (on and dc_ok()) ? "auto" : "off");
        setprop("controls/fuel/stby-pump[" ~ i ~ "]",
                (getprop(FC ~ "stby-pump[" ~ i ~ "]") or 0) and cb("stby-pump[" ~ i ~ "]") and dc_ok());
    }
    crossfeed_switch();
    var sel = getprop(FC ~ "fuel-qty-select") or 0;
    foreach (var i; [0, 1]) {
        var lbs = 0;
        if (dc_ok()) {
            if (sel == -1) lbs = 1000;
            elsif (sel == 1) lbs = cb("fuel-qty-aux") ? (getprop("consumables/fuel/tank[" ~ (i == 0 ? 0 : 3) ~ "]/level-lbs") or 0) : 0;
            else lbs = cb("fuel-qty-main") ? (getprop("consumables/fuel/tank[" ~ (i == 0 ? 1 : 2) ~ "]/level-lbs") or 0) : 0;
        }
        var n = props.globals.getNode("sim/model/fusion/fuel-qty-ind[" ~ i ~ "]", 1);
        n.setDoubleValue((n.getValue() or 0) + (lbs - (n.getValue() or 0)) * 0.15);
    }
};

# ---------------------------------------------------------------------------
# keep the cockpit switches in step with systems changed elsewhere (menus, automatic start, keyboard)
# ---------------------------------------------------------------------------
var sync_switches = func {
    foreach (var i; [0, 1]) {
        var g = fc.getNode("gen[" ~ i ~ "]", 1);
        var tie = elec.getNode("engine[" ~ i ~ "]/bus-tie", 1).getBoolValue();
        if ((g.getValue() or 0) >= 0 and (g.getValue() == 1) != tie) g.setIntValue(tie ? 1 : 0);
        var s = fc.getNode("start[" ~ i ~ "]", 1);
        var st = getprop("controls/engines/engine[" ~ i ~ "]/starter");
        if (s.getValue() == 0 and st) s.setIntValue(1);
        elsif (s.getValue() == 1 and !st) s.setIntValue(0);
        var w = fc.getNode("wshld[" ~ i ~ "]", 1);
        var heat = getprop("controls/anti-ice/window-heat[" ~ i ~ "]");
        if ((w.getValue() != 0) != (heat ? 1 : 0)) w.setIntValue(heat ? 1 : 0);
        var b = fc.getNode("bleed[" ~ i ~ "]", 1);
        var ba = getprop("controls/pressurization/bleed-air[" ~ i ~ "]");
        if (ba and b.getValue() != 1) b.setIntValue(1);
        elsif (ba != nil and !ba and b.getValue() == 1) b.setIntValue(0);
    }
    var af = fc.getNode("autofeather", 1);
    var afp = getprop("controls/engines/autofeather");
    if (af.getValue() != -1 and (af.getValue() == 1) != (afp ? 1 : 0)) af.setIntValue(afp ? 1 : 0);
};

# ---------------------------------------------------------------------------
# init and loops
# ---------------------------------------------------------------------------
var DEFAULTS = [
    ["master-emer", 0], ["master-guard", 0], ["gen[0]", 0], ["gen[1]", 0], ["start[0]", 0], ["start[1]", 0],
    ["stby-display", 1], ["bus-sense", 0], ["gen-ties", 0], ["autofeather", 1], ["wshld[0]", 0], ["wshld[1]", 0],
    ["surface-deice", 0], ["bleed[0]", 1], ["bleed[1]", 1], ["cabin-warn-test", 0], ["fire-test[0]", 0],
    ["fire-test[1]", 0], ["window-defog", 0], ["prop-sync", 0], ["dg-free[0]", 0], ["dg-free[1]", 0],
    ["slew[0]", 0], ["slew[1]", 0], ["reversion-pfd1", 0], ["reversion-mfd", 0], ["reversion-pfd2", 0],
    ["ahs-source", 1], ["ads-source", 1], ["inhibit-pfd1", 0], ["inhibit-mfd", 0], ["inhibit-pfd2", 0],
    ["couple", 0], ["vnav", 0], ["radio-call", 0], ["env/mode", 1], ["env/blower-cockpit", 0], ["env/blower-cabin", 0],
    ["env/man-temp", 0], ["cb/landing-gear-relay", 0], ["extinguisher[0]", 0], ["extinguisher[1]", 0],
    ["ccp[0]/display", 0], ["ccp[1]/display", 0], ["elec-trim", 1], ["cabin-press", 0], ["stall-test", 0],
    ["gear-warn-test", 0], ["cvr-test", 0], ["annun-dim", 0], ["cabin-signs", 0], ["cabin-lights", 0],
    ["crossfeed", 0], ["stby-pump[0]", 0], ["stby-pump[1]", 0], ["aux-xfer[0]", 0], ["aux-xfer[1]", 0],
    ["fuel-qty-select", 0],
];
var DEFAULTS_D = [["env/temp-cockpit", 0.5], ["env/temp-cabin", 0.5], ["env/man-heat", 0.5], ["friction[0]", 0.3],
                  ["friction[1]", 0.3]];

var init = func {
    setprop("sim/model/fusion/enabled", 1);
    foreach (var d; DEFAULTS) {
        var n = fc.getNode(d[0], 1);
        if (n.getValue() == nil) n.setIntValue(d[1]);
    }
    foreach (var d; DEFAULTS_D) {
        var n = fc.getNode(d[0], 1);
        if (n.getValue() == nil) n.setDoubleValue(d[1]);
    }
    foreach (var k; [0, 1]) {
        var a = "controls/fusion/audio[" ~ k ~ "]/";
        foreach (var d; [["xmit", 0], ["filter", 1], ["emer", 0], ["mic-oxy", 0], ["mkr-hi", 1]])
            if (getprop(a ~ d[0]) == nil) setprop(a ~ d[0], d[1]);
        if (getprop(a ~ "master-vol") == nil) setprop(a ~ "master-vol", 0.8);
        foreach (var r; keys(RX)) {
            if (getprop(a ~ r) == nil) setprop(a ~ r, (k == 0 and (r == "comm1" or r == "mkr")) ? 1 : 0);
            if (getprop(a ~ r ~ "-vol") == nil) setprop(a ~ r ~ "-vol", 0.7);
        }
        setprop("controls/engines/engine[" ~ k ~ "]/auto-ignition", getprop("controls/engines/engine[" ~ k ~ "]/auto-ignition") != 0);
    }
    if (getprop("instrumentation/altimeter[1]/setting-inhg") == nil)
        setprop("instrumentation/altimeter[1]/setting-inhg", getprop("instrumentation/altimeter/setting-inhg") or 29.92);
    setprop("systems/oxygen/bottle-psi", 1850);
    foreach (var k; [0, 1, 2]) {
        if (getprop("sim/model/fusion/display-brightness[" ~ k ~ "]") == nil) setprop("sim/model/fusion/display-brightness[" ~ k ~ "]", 1.0);
        if (getprop("sim/model/fusion/flood[" ~ k ~ "]") == nil) setprop("sim/model/fusion/flood[" ~ k ~ "]", 0.0);
    }
    sync_switches();

    foreach (var i; [0, 1]) {
        (func(i) {
            setlistener(FC ~ "gen[" ~ i ~ "]", func gen_switch(i), 0, 0);
            setlistener(FC ~ "start[" ~ i ~ "]", func start_switch(i), 0, 0);
            setlistener(FC ~ "wshld[" ~ i ~ "]", func wshld_switch(i), 0, 0);
            setlistener(FC ~ "bleed[" ~ i ~ "]", func bleed_switch(i), 0, 0);
        })(i);
    }
    setlistener(FC ~ "master-emer", master_emer, 0, 0);
    setlistener("controls/electric/battery-switch", func(n) {
        if (n.getBoolValue() and getprop(FC ~ "master-emer")) n.setBoolValue(0);
    }, 0, 0);
    setlistener(FC ~ "autofeather", autofeather_switch, 0, 0);
    setlistener(FC ~ "surface-deice", surface_deice, 0, 0);
    setlistener(FC ~ "cabin-warn-test", cabin_test, 0, 0);
    setlistener(FC ~ "gen-ties", func { setprop("controls/electric/gen-ties-man-close", (getprop(FC ~ "gen-ties") or 0) == 1); }, 0, 0);
    setlistener(FC ~ "bus-sense", func {
        var v = getprop(FC ~ "bus-sense") or 0;
        setprop("instrumentation/annunciators/warning/test", v == 1);
        setprop("controls/electric/bus-sense-reset", v == -1);
    }, 0, 0);
    setlistener(FC ~ "cabin-press", cabin_press, 0, 0);
    setlistener(FC ~ "cabin-signs", cabin_signs, 0, 0);
    setlistener(FC ~ "ahs-source", func(n) { gui.popupTip("Pilot PFD attitude / heading: AHRS " ~ (n.getValue() ? "1" : "2")); }, 0, 0);
    setlistener(FC ~ "ads-source", func(n) { gui.popupTip("Pilot PFD air data: ADC " ~ (n.getValue() ? "1" : "2")); }, 0, 0);

    fast_timer.start();
    slow_timer.start();
    print("KingAir-350ER: Pro Line Fusion cockpit ok");
};

var fast = func {
    update_lighting();
    update_cbs();
    update_power_levers();
    update_gear_horn();
    update_cvr(0.1);
    update_lamps();
    update_ahrs(0.1);
    update_static();
    update_prop_sync();
};
var slow = func {
    sync_switches();
    update_audio();
    update_cabin(0.5);
    update_fuel();
    setprop("systems/oxygen/pressure-psi", (dc_ok() and cb("oxygen")) ? (getprop("systems/oxygen/bottle-psi") or 0) : 0);
    update_hobbs(0.5);
    update_vnav();
};
var fast_timer = maketimer(0.1, fast);
var slow_timer = maketimer(0.5, slow);

aircraft.data.add("sim/model/fusion/hobbs-hours");
setlistener("sim/signals/fdm-initialized", func { settimer(init, 0.5); }, 0, 0);
