import bemt2, math, numpy as np
from bemt2 import R, B, hub, r_c, c_in, twist_rel, element
_sec0=bemt2.section
def section_inv(alpha_deg, M):
    # inverted airfoil (reverse flow): mirror camber
    cl,cd=_sec0(-alpha_deg, M); return -cl, cd
def reverse_static(beta75, n_rps=1700/60.0, rho=0.002377, a_snd=1116.0, nseg=30):
    D=2*R; omega=2*math.pi*n_rps; V=0.003*n_rps*D
    xs=np.linspace(hub,1.0,nseg+1); xm=0.5*(xs[1:]+xs[:-1]); dx=(xs[1:]-xs[:-1])*R
    T=0.0;Q=0.0
    for x,dr in zip(xm,dx):
        r=x*R; c=np.interp(x,r_c,c_in)/12.0; bl=beta75+twist_rel(x); lam=V/(omega*r)
        Wref=lambda phi: math.hypot(V,omega*r)/a_snd
        if bl<0:
            # mirrored frame with inverted airfoil
            orig=bemt2.section; bemt2.section=section_inv
            phi,a,b,sigma=element(x,-bl,lam,Wref)
            Va=V*(1+a); Vt=omega*r*(1-b); W=math.hypot(Va,Vt); phi2=math.atan2(Va,Vt)
            alpha=math.radians(-bl)-phi2; cl,cd=section_inv(math.degrees(alpha),W/a_snd)
            bemt2.section=orig
            Cn=cl*math.cos(phi2)-cd*math.sin(phi2); Ct=cl*math.sin(phi2)+cd*math.cos(phi2)
            T-=0.5*rho*W*W*B*c*Cn*dr; Q+=0.5*rho*W*W*B*c*Ct*r*dr
        else:
            phi,a,b,sigma=element(x,bl,lam,Wref)
            Va=V*(1+a); Vt=omega*r*(1-b); W=math.hypot(Va,Vt); phi2=math.atan2(Va,Vt)
            alpha=math.radians(bl)-phi2; cl,cd=bemt2.section(math.degrees(alpha),W/a_snd)
            Cn=cl*math.cos(phi2)-cd*math.sin(phi2); Ct=cl*math.sin(phi2)+cd*math.cos(phi2)
            T+=0.5*rho*W*W*B*c*Cn*dr; Q+=0.5*rho*W*W*B*c*Ct*r*dr
    n=n_rps
    return T/(rho*n*n*D**4), Q*omega/(rho*n**3*D**5)

Js=[0.0]+[round(0.2*i,1) for i in range(1,16)]+[3.5,4.0,5.0]
betas=[-15,-10,-5,0,5,10,15,20,25,30,35,40,45,50,55,60,70,80,87]
CT=np.zeros((len(Js),len(betas))); CP=np.zeros_like(CT)
for j,b in enumerate(betas):
    if b<0:
        ct0,cp0={-5:(-0.035,0.035),-10:(-0.11,0.11),-15:(-0.19,0.20)}[b]
        for i,J in enumerate(Js):
            CT[i,j]=ct0*max(1-0.25*J,0.3); CP[i,j]=cp0*(1+0.2*J)
    else:
        for i,J in enumerate(Js):
            ct,cp,T,Q=bemt2.bemt(J,b); CT[i,j]=ct; CP[i,j]=cp
# feather column: force near-zero thrust, positive (windmill-resisting) power
jf=betas.index(87)
for i,J in enumerate(Js):
    CT[i,jf]=-0.004-0.002*J
    CP[i,jf]=max(CP[i,jf],0.05)
# smooth the 80 column toward feather a bit
np.set_printoptions(linewidth=250,precision=4,suppress=True)
print("CT\n",CT); print("CP\n",CP)
n=1700/60; rho=0.002377; D=8.75
print("reverse static thrust at beta -12 (interp):", np.interp(-12,betas,CT[0])*rho*n*n*D**4, " Cp", np.interp(-12,betas,CP[0]), "-> hp", np.interp(-12,betas,CP[0])*rho*n**3*D**5/550)
def fmt(M):
    s="            "+"".join(f"{b:10d}" for b in betas)+"\n"
    for J,row in zip(Js,M):
        s+=f"     {J:6.2f}   "+"".join(f"{v:10.4f}" for v in row)+"\n"
    return s
xml=f'''<?xml version="1.0"?>
<!--
  Hartzell HC-E4A-3 style 4-blade, 105 in aluminium propeller for the Beechcraft King Air 350 (PT6A-60A)
  Generated by blade-element/momentum theory (bemt2.py / gen_prop2.py), blade angle referenced at 0.75 R.
  Columns: blade angle (deg); rows: advance ratio J = V/(n D).
  minpitch  = flight-idle low pitch stop, reversepitch = max reverse, maxpitch = feather.
  Governor range 1450-1700 rpm (prop lever), gear ratio 1 (engine RPM property = propeller RPM).
-->
<propeller name="Hartzell-4B-105in">
  <ixx unit="SLUG*FT2"> 21.0 </ixx>
  <diameter unit="IN"> 105.0 </diameter>
  <numblades> 4 </numblades>
  <gearratio> 1.0 </gearratio>
  <p_factor> 6.0 </p_factor>
  <sense> 1 </sense>
  <minpitch> 7.5 </minpitch>
  <maxpitch> 87 </maxpitch>
  <reversepitch> -12 </reversepitch>
  <minrpm> 1450 </minrpm>
  <maxrpm> 1700 </maxrpm>
  <constspeed> 1 </constspeed>

  <table name="C_THRUST" type="internal">
    <tableData>
{fmt(CT)}    </tableData>
  </table>

  <table name="C_POWER" type="internal">
    <tableData>
{fmt(CP)}    </tableData>
  </table>

  <!-- helical tip Mach effects -->
  <table name="CT_MACH" type="internal">
    <tableData>
      0.80   1.00
      0.90   0.95
      1.00   0.85
      1.10   0.75
    </tableData>
  </table>
  <table name="CP_MACH" type="internal">
    <tableData>
      0.80   1.00
      0.90   1.08
      1.00   1.30
      1.10   1.50
    </tableData>
  </table>
</propeller>
'''
open('../Engines/Hartzell-4B-105.xml','w').write(xml)
print("written")
